function [performance_index_em,performance_em_pertime,confusion_matrix_em_pertime,em_estimate_state_series_block,parameter_em_pertime,likelihood_function_pertime]=AuxFun_SaveMatForPython(performance_structure_data)

performance_index_em=performance_structure_data.performance_index_em;
performance_em_pertime=performance_structure_data.performance_em_pertime;
confusion_matrix_em_pertime=performance_structure_data.confusion_matrix_em_pertime;
em_estimate_state_series_block=performance_structure_data.em_estimate_state_series_block;
parameter_em_pertime=performance_structure_data.parameter_em_pertime;
likelihood_function_pertime=performance_structure_data.likelihood_function_pertime;


end